### ISSUE TITLE
Hacktoberfest: Multimodal search demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-multimodal-search#1]
This is the tracker for polishing the “Dog image search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Fixes for any of the identified issues 
    - [x] Error: Search by image fails with error FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/dog.jpg
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [x] used Weaviate modules/ML models
    - [ ] Replace screenshots of demo usage with short demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Origin of Dataset (claimed by @VishalPraneeth )
- [ ] Possible improvements/enhancements
    - [ ] Incorporate CSS styling (e.g., with [bootstrap](https://getbootstrap.com/) or [tailwind](https://tailwindcss.com/)
    - [ ] Extend existing tests
    - [ ] Add progress bar to import file
    - [ ] Explore adding text to the vector database (See last note in "usage instructions."
    - [x] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image
    - [ ] Add usage of [new multimodal model](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/multi2vec-bind)
    - [ ]  Replace current sample data with a larger dataset (e.g., from Kaggle)

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by miniMaddy** [comment]
I am working on this issue. Please assign this to me. Thank You!

**Comment by iamleonie** [comment]
@miniMaddy Thank you for volunteering. Please let others know what you plan on working on so others can collaborate without doing double work.

**Comment by miniMaddy** [comment]
I will be working from running the demo and fixing any identifies issues if any. I will also be working on the possible improvements.

**Comment by lalit-k** [comment]
@iamleonie I will be trying the demo and then will conversion to new Weaviate Python Client. thanks!

**Comment by lalit-k** [comment]
@iamleonie I ran this demo and identified an issue, will be working on fixing it before moving to conversion to new Weaviate Python Client.

Issue:
Search by image fails with error `FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/dog.jpg`

**Comment by iamleonie** [comment]
Thank you @lalit-k, for your contribution. Let's take a moment to align with @miniMaddy to avoid any code conflicts:

@miniMaddy Could you please let us know which of the possible improvements you are working on? 
@lalit-k Since the conversion to the new Python client are quite big changes, I have two ideas here to avoid merge conflicts later: 
1. Maybe it would be a good idea to wait for the conversion to the new Python client after @miniMaddy's changes are available
2. Alternatively, it would be great if you could collaborate with @miniMaddy to convert their changes into the new Python client.

Thank you!

**Comment by miniMaddy** [comment]
Hello, @lalit-k , let's connect on Weaviate's Slack, it will be easier to communicate.

**Comment by miniMaddy** [comment]
Also, @iamleonie, since the new Python client is in experimental phase right now, I was thinking of making a separate folder for it and not merge it with the main code till it's stable. What do you think?

**Comment by iamleonie** [comment]
Hey @miniMaddy, we were [discussing on Slack](https://weaviate.slack.com/archives/C05TR90PMT4/p1696579221084489?thread_ts=1696570870.673199&cid=C05TR90PMT4) with another contributor how we should approach this best.

> The upcoming releases (hopefully 1.22) of Weaviate should be compatible with the new client (v4), as the gRPC back-end will be added before the client is final. I think using a preview image is and just updating the requirements is fine, and aim to swap it out with the official release once it is launched.

So, we'd prefer to replace the old client with the new client instead of having a separate folder. 
Maybe, you could collaborate with @lalit-k, as they already created a [PR for the conversion to the new client for a different demo project which we are currently reviewing](https://github.com/weaviate-tutorials/DEMO-image-search-dogs/pull/4).

Please align in Slack or here (whatever is better for you) to have a clear picture of who is working on what to avoid double work and make this collaboration a great experience for everyone. Thank you so much!

**Comment by lalit-k** [comment]
Hi @iamleonie thank you for coordinating on this and your concerns on code conflicts.

I discussed this with @miniMaddy , and we both decided that I should make my changes on the conversion to the new client first. thanks!

**Comment by lalit-k** [comment]
Hi @iamleonie Finished up with my changes to new client. Changes are pushed into existing open PR https://github.com/weaviate-tutorials/DEMO-multimodal-search/pull/2

Please have a look. thanks

**Comment by iamleonie** [comment]
Hi @miniMaddy, @lalit-k,
I am trying to get an overview of who is currently working on what to make it easier for new contributors to find open tasks. Could you please let me know if you are currently working on any of the tasks in this issue?

Thank you so much!

**Comment by lalit-k** [comment]
@iamleonie I'm not working on any other tasks in this issue currently. Thanks!

**Comment by VishalPraneeth** [comment]
@iamleonie  I want to add the dataset license, is anyone else doing that?

**Comment by VishalPraneeth** [comment]
Hi @iamleonie can you please review the dataset

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
